name: lint

on:
  push:
    branches:
      - main
      - actions-test
  pull_request:
    branches:
      - main
      - actions-test

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [24]
        elixir: [1.13]
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Branch-Name
        uses: nelonoel/branch-name@v1.0.1

      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
          experimental-otp: true

      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Prepare
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix do deps.get, deps.compile

      - name: Run format
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo --strict -a
